---
title: "Spring 2026 outline"
format: html
editor: visual
embed-resources: true
---

## Course Outline

The following is an outline of weekly topics. The outline is tentative and subject to change.

## Schedule at a glance

Unless otherwise noted, readings refer to [Applied Statistics with R by Justin Touchon](https://global.oup.com/academic/product/applied-statistics-with-r-9780197797341?lang=en&cc=nl), which is available as an eText from CMU's library.

+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| Week      | Topic                       | Reading                                                      | Homework                                                                             |
+===========+=============================+==============================================================+======================================================================================+
| 1         | Intro to Course and RStudio | Ch. 1                                                        | [Install software](https://jpomz.github.io/ENVS318-Applied-R-NatSci/computer-setup/) |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 2         | Intro to R and the RxP data | Ch. 1, 3                                                     | Basic programming                                                                    |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 3         | Number Distributions        | [YouTube intro](https://www.youtube.com/watch?v=rzFX5NWojp0) | Distributions                                                                        |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 4         | Quarto                      | Ch. 3, 4                                                     | First Quarto file                                                                    |
|           |                             |                                                              |                                                                                      |
|           |                             | [R4DS: Quarto](https://r4ds.hadley.nz/quarto.html)           |                                                                                      |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 5         | Summary Stats               | Ch. 5.1-.6                                                   | Data summary                                                                         |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 6         | t-tests                     | Ch. 5.7                                                      | t-tests                                                                              |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 7         | ANOVA                       | Ch. 5.9-.10, 6.1-.4                                          | ANOVA                                                                                |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 8         | Tidy Data                   | Ch. 1.8, 2                                                   | Making data tidy                                                                     |
|           |                             |                                                              |                                                                                      |
|           |                             | [R4DS: Tidy](https://r4ds.hadley.nz/data-tidy.html)          |                                                                                      |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 9         | Linear Regression           | Ch. 5.5, 6.3-.6                                              | Linear regression                                                                    |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 10        | ANCOVA                      | Ch. 6.4-.7                                                   | ANCOVA                                                                               |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 11        | GLM                         | Ch. 7                                                        |                                                                                      |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 12        | Hierarchical models         | Ch. 8.1-.4                                                   |                                                                                      |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 13        | Project                     |                                                              | Find a data set                                                                      |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 14        | Project                     |                                                              | Summarize data set, outline analysis                                                 |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 15        | Project                     |                                                              | Nothing due, work on analysis                                                        |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+
| 16        | Final                       |                                                              | Full analysis due                                                                    |
+-----------+-----------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------+

## Detailed outline

1.  W1: Intro to course and RStudio.

    -   Course syllabus and policies

    -   Grade

        -   Homework

        -   Final project

    -   Software installation

    -   R Studio Project

        -   Setup

        -   File structure

        -   Options

    -   Assignment

        -   Software installation

        -   Class R Studio Project setup

2.  W2: Intro to R and RxP data.

    -   Intro to R

        -   Basic Programming

        -   Objects

            -   Types

            -   Saving/modifying objects

        -   Functions

        -   Tidy data

    -   `RxP.csv` data

        -   Introduction

        -   Basic data exploration, manipulation, and visualization

    -   Assignment

        -   Basic exploration, visualization, and manipulation of the `galapago-finches.csv` data

3.  W3: Quarto

    -   What is Quarto?

    -   Making a Quarto document

    -   Rendering to html

    -   Document YAML

    -   Text format

    -   Code blocks

        -   options

4.  W4: Number Distributions.

    1.  Normal distribution

        1.  Describe it

        2.  Compare normal distributions

    2.  Empirical rule

    3.  R functions: `_norm()`

    4.  Standard normal and z-scores

    5.  Some other distributions and transformations

5.  W5: Summary Statistics.

    1.  Populations vs samples

        1.  Parameters vs. estimates

    2.  Summarize data

        1.  Location and Spread

    3.  Inferential stats

        1.  SE

    4.  Is my data normal?

        1.  Compare density and boxplots

        2.  Formal tests of distributions

    5.  Log-transformation

6.  W6: Comparing two means.

    1.  Hypothesis testing

    2.  Introduction to the t-test

        1.  1- and 2-tailed tests

            1.  Generally 2-tailed in this course

    3.  Different types of t-tests

        1.  one-, two-sample, and paired t-tests

    4.  functions

        1.  `t.test()`

        2.  `lm()`

    5.  Data format

        1.  One-sample t-test - same for both functions

            1.  `function(y ~ 1, data = data)`

            2.  Testing to see if y is different from 0

            3.  If you want to test another value (i.e., stream pH different from 7?):

                1.  `function(y - 7 ~ 1, data = data)`

        2.  two sample - same for both functions

            1.  y = response column, x = "group" column

            2.  `function(y~x, data = data)`

        3.  Paired

            1.  X and y are two vectors:

                1.  `t.test(x, y, paired = TRUE)`

            2.  y = response and x = group (i.e., before/after)

                1.  `t.test(y ~ group, paired = TRUE, data = data)`

            3.  Calculate the difference in each pair

                1.  i.e., `diff = before - after`

                2.  both: `function(diff ~1, data = data)`

7.  W7: Comparing multiple means.

    1.  Basic, one-way ANOVA

        1.  Post-hoc pairwise comparisons

    2.  ANOVA with multiple Factors

    3.  Two-way ANOVA with interaction

    4.  Pairwise comparisons with other ANOVAs

8.  W8: Tidy Data.

9.  W9: Linear Regression.

    1.  Fitting

    2.  Predicting

10. W10: ANCOVA - combining ANOVA and Linear Regression.

    1.  Type 1, 2, and 3 tests

11. W11: Generalized Linear Models - When your response is non-normal.

12. W12: Hierarchical Models.

13. Project: Find a dataset.

14. Project: Summarize your data.

15. Project: Analyze your data.

16. Final: Submit full analysis.
