---
title: "Lecture Week 1: Course Intro"
format: 
  html:
    embed-resources: true
editor: visual
toc: true
toc-depth: 2
number-sections: true
theme:
  light: flatly
  dark: darkly
---

## Overview

This week we will introduce the course, go over the syllabus and set up our R Studio project for the course.

## Outline

-   Lecture meeting Location and time: WS 245, MWF 2-2:50 PM

-   Office Hours:

### About me

-   Leadville, Red Rocks CC, CSU, UC in NZ

### About you

-   Name, Class, Favorite animal, what your hoping to get out of this course

### Course Objectives - *Applied* statistics

-   Practical information for analyzing data

-   How to get data into R

-   Explore, manipulate, visualize

-   Summarize

-   Statistical analysis and interpretation

-   Study design

-   secondary objective interspersed throughout course

### Software

-   R and Rstudio

-   Download before next class (instructions at end)

-   Spreadsheet software

### Why R

-   In demand skill

-   Versatile

-   It is the future

-   Applied stats

-   don't waste your time calculating by hand

-   Have more time to do better science

-   Class mantra:

> ***Work hard, learn a game-changing tool for your research, and have an incredibly in-demand skill to help land you a job!***

### Course structure

-   Weekly topic

    -   Overview

    -   Examples

    -   Interpretation

-   **Live Coding in front of the class**

-   Open time to work on HW in class

### Course Grade

-   11 graded homework assignments (70% of grade)

    -   1 homework grade will be dropped

    -   10 HWs each worth \~7% of your final grade

-   Final project (30% of grade)

    -   last 3 weeks of course

    -   3 "mini" assignments

        -   Find a data set (5%)

        -   Summarize data and outline analysis (10%)

        -   Full analysis (15%)

### Weekly homework assignment

-   Homework is due by Sunday at 11:59 PM

-   Automatic grace period of 2 days with no late penalty

-   Homework solutions will be posted on D2L Wednesday morning

-   Assignment submissions after the the solutions have been posted will receive a 50% penalty

-   I will attempt to provide *some* time to work on HW in class each week

-   Start HW early, bring questions to class

### Homework grading rubric

-   Completion (up to 50%)

-   Accuracy (up to 40%)

    -   A subset of the questions will be graded in detail

    -   I will look for correct values, plots, interpretation, etc.

-   Syntax (up to 10%)

    -   Does the code run (regardless of answer/value/output)?

    -   Is all superfluous code removed?

-   Late penalty

    -   50% penalty for submissions made after the grace period.

| Attribute    | Full points                                                                                                       | Most points                                                                                                                                                | Partial points                                                                                                       | No Points                                                                                                                                         |
|--------------|-------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| Completeness | 5 points. Complete assignment is submitted. An attempt is made to answer all questions.                           | 3 points. At least half the assignment is complete. An attempt is made to answer most questions                                                            | 2 Point. Less than half the assignment is complete.                                                                  | 0 Points. Assignment is not turned in.                                                                                                            |
| Values       | 4 points. All the graded parts are correct. The values/plots/interpretations match the solution key.              | 3 points. Most of the graded sections are correct and match the solution key.                                                                              | 2 points. Some of the graded sections are correct and match the solution key.                                        | 0 points. None of the graded sections are correct and match the solution key.                                                                     |
| Syntax       | 1 point. All code runs correctly. There is no superfluous code in the document. Quarto documents render correctly | 0.9 points. Nearly all code runs correctly, with only a minor error and/or very little superfluous code in the document. Quarto documents render correctly | 0.5 points. Not all the code runs correctly. There are a few minor or one major errors and/or some superfluous code. | 0 points. Very little or none of the code runs correctly. There are several minor or more than two major errors and/or excessive superfluouscode. |

### Readings

-   [Applied Statistics with R](https://global.oup.com/academic/product/applied-statistics-with-r-9780197797341?lang=en&cc=nl), 2nd ed. by Justin Touchon

-   Available from CMU library

-   Other free, online readings as assigned

-   Readings are optional and for your own personal edification

## Software Installation

1.  [Download R](https://cran.rstudio.com/)

    -   click appropriate link (Windows, Mac, Linux) for your machine near the top of the page

2.  [Download R Studio](https://posit.co/download/rstudio-desktop/)

## Project setup

### Create Project

1.  Create an ENVS475 folder somewhere on your computer\

-   Could be on Desktop, in your Documents, etc.\
-   Doesn't matter, as long as you know where it is.

2.  Open RStudio\

3.  Click on `File` --\> `New Project` --\> `Existing Directory` then `Browse` and select your "ENVS475" Folder.

4.  Check that you can see "ENVS475" in the top right corner of RStudio

-   When you are taking notes in class, working on homework assignments, etc., **ALWAYS MAKE SURE YOU ARE IN THE CORRECT PROJECT!** i.e., check that is says "ENVS475" in top right corner

#### Worskpace save option: Never

-   **Never** save your work space image
-   Click on `Tools` --\> `Global Options` and select the `General` tab\
-   Under the "Save workspace to .Rdata on exit:" option, select `Never`

#### Saving scripts

-   Always manually save the script you're working on by clicking on the floppy disk icon or pressing `Ctrl` + `S` on a laptop or `Cmd` + `S` on a Mac

#### Open project

-   Always make sure to open up the *project* (icon is a little blue box with R inside of it, and file extension is `.Rproj`) at the beginning of class or when you're working on it at home\
-   If you try to just open up a script, it will open it in "project-none" directory
    -   When you save, it will go to whatever default directory is set up
    -   In other words, it may be hard to find, and you would then need to copy/paste your updated document back into your project\
    -   Avoid this by always opening up the project

### Organize Project with Subfolders

-   In the "Files" pane, press the `New Folder` button and create the following folders (make sure spelling/capitalization matches exactly):
    -   `Scripts`\
    -   `Data`\
    -   `Assignments`\
    -   `Other_Resources`

#### File names

-   R doesn't always do well with spaces in file names

-   avoid potential issues by using "\_" or "-" in file names instead of spaces\

-   Don't use any other special characters like `.`, `,`, `@`, `!`

-   Don't begin a file name with a number

-   **Do**:

    -   "Other_resources"
    -   "last-name_homework-1"
    -   "data-table-notes"

-   **Do NOT**:

    -   "Other resources"
    -   "2nd week home work, lastname"

### Scripts

-   Take notes and write code live demo'd in class\
-   Make a new script by clicking the `New File` button or using the `Ctrl-Shift-N` keyboard shortcut (`Cmd-Shift-N`) on Mac
    -   Add the following code to your script:

```         
# my first script
2+2
x = 5
x
```

-   save your script by clicking on the floppy disk icon or pressing `Ctrl` + `S` on a laptop or `Cmd` + `S` on a Mac\
-   name the file "my-first-script.R' and make sure to save it in your"Scripts" folder

### Data

-   Save all necessary data files here\
-   We will be working with lots of data files in this class
    -   Most files will be comma-separated-value files or plain text files (.csvor .txt file extensions, respectively)
-   Go to the [Datasets](%7B%7B%20site.baseurl%7D%7D/materials/datasets) section of the website and download the "Portal Surveys csv" file\
-   Make sure to save the file in the "Data" folder and that the name is "surveys.csv"\
-   Go to the "Files" pane in Rstudio and make sure you can see the `surveys.csv` file in the Data folder

### Libraries

Run the following line of code once on each machine you will use:

`install.packages(c("tidyverse", "lme4", "multcomp", "car", "MASS", "here", "fitdistrplus", "broom", "cowplot", "emmmeans", "aod", "lmtest", "qqconf"))`

::: callout-important
-   You only need to install the package ONCE

-   Every time you start/open R Studio, you need to load the packages by using the `library()` function

-   i.e., at the top of each script you write, you should have something like the following:

    -   `library(tidyverse)`

    -   `library(MASS)`

    -   etc.
:::

### Download Data

-   In lecture, we will primarily be working with the `RxP.csv` data.

-   [Download the data here](https://global.oup.com/booksites/fdscontent/booksites/uk/booksites/content/9780198869979/RxP.csv)

    -   Be sure to put it in your `data/` folder

-   Homework assignments will generally require other data files

    -   The top of each assignment will clearly indicate which data is needed

    -   Where to get it from

    -   Generally found on D2L

## First assignment

1.  Download R

2.  Download R Studio

3.  Make an ENVS475 project

4.  Download libraries (see above)

5.  Copy and run the following code

```{r}
#| warning: false
library(tidyverse)
data("starwars")
starwars |>
  filter(homeworld == "Tatooine") |>
  select(name) |>
  unique()
```

6.  Show your instructor that your output matches the example above
